// Ambient declarations for the generated backend module.
// The real backend.ts is generated by the Caffeine build pipeline.
// This stub satisfies TypeScript's module resolution during development.

declare module "./backend" {
  export interface Subject {
    id: bigint;
    name: string;
    batchType: string;
    displayOrder: bigint;
  }

  export interface Video {
    id: bigint;
    title: string;
    description: string;
    videoUrl: string;
    subjectId: bigint;
    displayOrder: bigint;
    createdAt: bigint;
  }

  export interface backendInterface {
    adminLogin(
      username: string,
      password: string,
    ): Promise<{ ok: string } | { err: string }>;
    adminLogout(token: string): Promise<{ ok: null } | { err: string }>;
    verifyToken(token: string): Promise<boolean>;
    getLogoUrl(): Promise<string>;
    setLogoUrl(
      token: string,
      url: string,
    ): Promise<{ ok: null } | { err: string }>;
    getSubjectsByBatch(batchType: string): Promise<Subject[]>;
    getSubjectById(id: bigint): Promise<Subject | null>;
    addSubject(
      token: string,
      name: string,
      batchType: string,
      displayOrder: bigint,
    ): Promise<{ ok: Subject } | { err: string }>;
    editSubject(
      token: string,
      id: bigint,
      name: string,
      batchType: string,
      displayOrder: bigint,
    ): Promise<{ ok: Subject } | { err: string }>;
    deleteSubject(
      token: string,
      id: bigint,
    ): Promise<{ ok: null } | { err: string }>;
    getAllSubjects(): Promise<Subject[]>;
    getVideosBySubject(subjectId: bigint): Promise<Video[]>;
    getVideoById(id: bigint): Promise<Video | null>;
    addVideo(
      token: string,
      title: string,
      description: string,
      videoUrl: string,
      subjectId: bigint,
      displayOrder: bigint,
    ): Promise<{ ok: Video } | { err: string }>;
    editVideo(
      token: string,
      id: bigint,
      title: string,
      description: string,
      videoUrl: string,
      subjectId: bigint,
      displayOrder: bigint,
    ): Promise<{ ok: Video } | { err: string }>;
    deleteVideo(
      token: string,
      id: bigint,
    ): Promise<{ ok: null } | { err: string }>;
    getAllVideos(): Promise<Video[]>;
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Uint8Array[]>;
    _caffeineStorageConfirmBlobDeletion(blobs: Uint8Array[]): Promise<void>;
    _caffeineStorageCreateCertificate(
      blobHash: string,
    ): Promise<{ blob_hash: string; method: string }>;
    _caffeineStorageRefillCashier(
      info: { proposed_top_up_amount?: bigint } | null,
    ): Promise<{ success?: boolean; topped_up_amount?: bigint }>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
  }

  export interface CreateActorOptions {
    agentOptions?: {
      identity?: unknown;
      host?: string;
    };
    agent?: unknown;
    processError?: (e: unknown) => never;
  }

  export class ExternalBlob {
    static fromURL(url: string): ExternalBlob;
    getBytes(): Promise<Uint8Array>;
    onProgress?: (progress: number) => void;
  }

  export function createActor(
    canisterId: string,
    uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
    downloadFile: (bytes: Uint8Array) => Promise<ExternalBlob>,
    options?: CreateActorOptions,
  ): Promise<backendInterface>;
}
